### ISSUE TITLE
exernallib.php error

### ISSUE THREAD

**Issue by thepurpleblob** [Annoto/moodle-local_annoto#9] opened 2019-10-03 13:38 UTC
Noticing lots of these in the logs...

Debugging: External function parameters: invalid OPTIONAL value specified. in 
* line 712 of /lib/externallib.php: call to debugging()
* line 46 of /local/annoto/externallib.php: call to external_function_parameters->__construct()
* line 68 of /local/annoto/externallib.php: call to local_annoto_external::get_jsparams_parameters()
* line 244 of /lib/externallib.php: call to local_annoto_external::get_jsparams()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()
, referer: http://pc164-239.cent.gla.ac.uk/moodle37/user/index.php?id=22

**Comment by ilyaDymshits** [comment] 2019-10-15 10:34
Сan you please add some data (on which page the error, system version..), I can’t follow the link and track this error.

**Comment by genadis** [comment] 2019-11-03 14:16
@thepurpleblob can you please verify if the issue is solved?

**Comment by thepurpleblob** [comment] 2019-11-03 22:16
I'll try to find time this week and will let you know

**Comment by genadis** [comment] 2020-05-12 12:52
Closing this. If there is still issue will be happy to reopen and investigate.

**Closed by genadis** 2020-05-12 12:52 UTC
Labels: help wanted, question
